---
title: DC Gay Flag Football League
description: Founded in 1994, DC Gay Flag Football League (DCGFFL) is DC's only gay flag football league with 20 teams and over 270 players.
meta_img:
twitter:
favicon:
url:
gtm:
schema:
  name: 
  type: 
  image: 
  logo:
  phone: 
  email: 
  social:
  location: 
    address: 
    city: 
    state: 
    zip: 
  hours:
    days:
    opens:
    closes:  
timezone: America/New York
future: true
markdown: kramdown
kramdown:
  auto_ids: false
exclude:
- Gemfile
- Gemfile.lock
- node_modules
- gruntfile.js
sass:
  sass_dir: _sass
  style: compressed
plugins:
  - jekyll-sitemap
collections:
  pages: 
    output: true
  events: 
    output: true
  games: 
    output: true
    sitemap: false
  teams: 
    output: true
    permalink: /teams/:title/    
  sponsors: 
    output: true
    sitemap: false  
  playoffs:
    output: true
    sitemap: false
    permalink: /playoffs/:title/ 
  rec-games: 
    output: true
    sitemap: false
  rec-teams: 
    output: true
    sitemap: false    
    permalink: /recreation-league/teams/:title/
  rec-playoffs:
    output: true
    sitemap: false
    permalink: /recreation-league/playoffs/:title/   
defaults:
- scope:
    type: 'pages'
  values:
    layout: default
- scope: 
    type: 'teams'
  values: 
    layout: team
- scope: 
    type: 'playoffs'
  values:
    layout: playoff
- scope: 
    type: 'rec-playoffs'
  values:
    layout: playoff          
- scope: 
    type: 'rec-teams'
  values: 
    layout: team