---
title: DC Gay Flag Football League
description: Founded in 1994, DC Gay Flag Football League (DCGFFL) is DC's only gay flag football league with 20 teams and over 270 players.
meta_img: 
twitter:
favicon: /img/dcgffl-favicon.png
url: https://dcgffl.org
gtm:
schema:
  name: 
  type: 
  image: 
  logo:
  phone: 
  email: 
  social:
  location: 
    address: 
    city: 
    state: 
    zip: 
  hours:
    days:
    opens:
    closes:  
timezone: America/New York
future: true
markdown: kramdown
kramdown:
  auto_ids: false
exclude:
- Gemfile
- Gemfile.lock
- node_modules
- gruntfile.js
sass:
  sass_dir: _sass
  style: compressed
plugins:
  - jekyll-sitemap
collections:
  pages: 
    output: true
  redirects: 
    output: true  
  events: 
    output: true
    permalink: /events/:title/
  games: 
    sitemap: false
  teams: 
    output: true
    permalink: /teams/:title/    
  locations: 
    sitemap: false
  sponsors: 
    output: true
    sitemap: false  
  playoffs:
    output: true
    sitemap: false
    permalink: /playoffs/:title/ 
  rec-games: 
    output: true
    sitemap: false
  rec-teams: 
    output: true
    sitemap: false    
    permalink: /recreation-league/teams/:title/
  rec-playoffs:
    output: true
    sitemap: false
    permalink: /recreation-league/playoffs/:title/
  posts: 
    output: true
    sitemap: true
    permalink: /:title/
  past-seasons: 
    output: true
    permalink: /past-seasons/:title/  
  power-rankings: 
    output: true  
defaults:
- scope:
    type: 'pages'
  values:
    layout: default
- scope: 
    type: 'teams'
  values: 
    layout: team
- scope: 
    type: 'playoffs'
  values:
    layout: playoff
- scope: 
    type: 'rec-teams'
  values: 
    layout: team
- scope: 
    type: 'rec-playoffs'
  values: 
    layout: playoff       
- scope: 
    type: 'posts'
  values:
    layout: post
- scope: 
    type: 'events'
  values: 
    layout: event        
- scope: 
    type: 'past-seasons'
  values: 
    layout: past-seasons    
- scope: 
    type: 'power-rankings'
  values: 
    layout: power-rankings
- scope: 
    type: 'redirects'
  values: 
    layout: redirect          