---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: _events
  label: Events
  create: documents
  match: "**/*"
  templates:
  - event
- type: directory
  path: _games
  label: Games
  create: documents
  match: "**/*"
  templates:
  - game
- type: directory
  path: _locations
  label: Locations
  create: documents
  match: "**/*"
  templates:
  - location
- type: document
  path: _data/menu.yml
  label: Menu
- type: jekyll-posts
  label: News
  create: documents
  templates:
  - news
- type: directory
  path: _pages
  label: Pages
  create: documents
  match: "**/*"
  templates:
  - basic-page
- type: directory
  path: _past-seasons
  label: Past Seasons
  create: documents
  match: "**/*"
  templates:
  - past-season
- type: directory
  path: _playoffs
  label: Playoffs
  create: documents
  match: "**/*"
  templates:
  - playoff
- type: directory
  path: _power-rankings
  label: Power Rankings
  create: documents
  match: "**/*"
  templates:
  - power-ranking
- type: directory
  path: _rec-games
  label: Rec Games
  create: documents
  match: "**/*"
  templates:
  - game
- type: directory
  path: _rec-playoffs
  label: Rec Playoffs
  create: documents
  match: "**/*"
  templates:
  - playoff
- type: directory
  path: _rec-teams
  label: Rec Teams
  create: documents
  match: "**/*"
  templates:
  - team
- type: directory
  path: _redirects
  label: Redirects
  create: documents
  match: "**/*"
- type: directory
  path: _teams
  label: Teams
  create: documents
  match: "**/*"
  templates:
  - team
upload_dir: img
public_path: "/img"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - JEKYLL_ENV=staging
  preview_output_directory: _site
  install_dependencies_command: bundle install --path vendor/bundle
  preview_docker_image: forestryio/ruby:2.6
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    --incremental -d _site
